# Dependencies
highlighter:      rouge

# Setup
title:            Jan Abrell
tagline:          'Research Page'
description:      ''
url:              https://jabrell.github.io
baseurl:          /

paginate:         5
